name: WooNPCs
version: '${version}'
main: com.oolongho.woonpc.WooNPCs
api-version: '1.21'
folia-supported: true
author: oolongho
description: WooNPCs

dependencies:
  server:
    WooHolograms:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true

commands:
  woonpc:
    description: WooNPCs 管理命令
    usage: /woonpc <create|remove|list|...>
    permission: woonpc.admin
    aliases: [wn, npc]

permissions:
  woonpc.admin:
    description: 管理员权限
    default: op
